### ISSUE TITLE
Switch to CMake

### ISSUE THREAD

**Issue by tripulse** [tripulse/vsp#3]
Meson is simply a probonchona for cross-platform compilation. It asks for `pkg-config` in Windows, which is only available through either WSL or MinGW or Cygwin.

**Comment by tripulse** [comment]
Ain't gonna bother with pain.

**Comment by eli-schwartz** [comment]
FWIW, you don't *need* pkg-config.

```
meson wrap install sdl2
```

and git add/commit `subprojects/sdl2.wrap` -- meson will now use an internal copy of sdl2 *iff* it cannot find one via pkg-config (see the `meson setup --wrap-mode` option for preferring one or the other).

There is no pre-written wrap for fftw that I'm aware of but it should not be too hard to make one and publish it via https://mesonbuild.com/Wrap-dependency-system-manual.html for the sake of Windows users, I guess.

**Comment by tripulse** [comment]
Nice, I didn't know about this before. Honestly, I don't care about Windows users, I'm just going to serve them a MinGW compiled copy.

**Comment by eli-schwartz** [comment]
Even better :D if any Windows users ever ask about it, you can let them work on a fftw wrap.

**Comment by tripulse** [comment]
^
